import jsPDF from "jspdf";
import type { Plan } from "./api";

const ACCENT = [52, 211, 153] as const;   // green
const TEXT   = [230, 230, 230] as const;
const MUTED  = [140, 140, 140] as const;
const BG     = [15,  15,  15] as const;
const CARD   = [26,  26,  26] as const;
const LINE   = [45,  45,  45] as const;

const DAY_NAMES = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];

export function exportPlanToPDF(plan: Plan, userName = "NutriAI User") {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = 210;
  const MARGIN = 14;
  const COL = W - MARGIN * 2;

  function setColor(rgb: readonly [number,number,number]) {
    doc.setTextColor(rgb[0], rgb[1], rgb[2]);
  }
  function line(y: number) {
    doc.setDrawColor(LINE[0], LINE[1], LINE[2]);
    doc.setLineWidth(0.2);
    doc.line(MARGIN, y, W - MARGIN, y);
  }
  function rect(x: number, y: number, w: number, h: number, rgb: readonly [number,number,number]) {
    doc.setFillColor(rgb[0], rgb[1], rgb[2]);
    doc.rect(x, y, w, h, "F");
  }

  // ── Cover page ──────────────────────────────────────────────────────────
  rect(0, 0, W, 297, BG);

  // Top accent bar
  rect(0, 0, W, 2, ACCENT);

  // Logo area
  setColor(ACCENT);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("NUTRIAI", MARGIN, 20);

  // Title
  setColor(TEXT);
  doc.setFontSize(36);
  doc.setFont("helvetica", "bold");
  doc.text("Your 7-Day", MARGIN, 60);
  doc.text("Diet Plan", MARGIN, 76);

  setColor(MUTED);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Prepared for ${userName}`, MARGIN, 92);
  doc.text(`Generated ${new Date(plan.generatedAt).toLocaleDateString("en-GB", { day:"numeric", month:"long", year:"numeric" })}`, MARGIN, 100);

  // Summary stats box
  rect(MARGIN, 120, COL, 44, CARD);
  const totalKcal = Math.round(
    plan.days.reduce((s, d) => s + d.meals.reduce((ms, m) => ms + m.kcal, 0), 0) / plan.days.length
  );
  const totalProtein = Math.round(
    plan.days.reduce((s, d) => s + d.meals.reduce((ms, m) => ms + m.protein, 0), 0) / plan.days.length
  );
  const totalCarbs = Math.round(
    plan.days.reduce((s, d) => s + d.meals.reduce((ms, m) => ms + m.carbs, 0), 0) / plan.days.length
  );
  const totalFat = Math.round(
    plan.days.reduce((s, d) => s + d.meals.reduce((ms, m) => ms + m.fat, 0), 0) / plan.days.length
  );

  const stats = [
    { v: `${totalKcal} kcal`, l: "Avg Daily Calories" },
    { v: `${totalProtein}g`, l: "Avg Protein" },
    { v: `${totalCarbs}g`, l: "Avg Carbs" },
    { v: `${totalFat}g`, l: "Avg Fat" },
  ];
  stats.forEach((s, i) => {
    const x = MARGIN + 6 + i * (COL / 4);
    setColor(ACCENT);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(s.v, x, 137);
    setColor(MUTED);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.text(s.l.toUpperCase(), x, 145);
  });

  // Footer on cover
  setColor(MUTED);
  doc.setFontSize(8);
  doc.text("All meals follow halal dietary guidelines · Generated by NutriAI", MARGIN, 285);

  // ── Day pages ────────────────────────────────────────────────────────────
  plan.days.forEach((dayData, di) => {
    doc.addPage();
    rect(0, 0, W, 297, BG);
    rect(0, 0, W, 2, ACCENT);

    let y = 16;

    // Day header
    setColor(MUTED);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text("NUTRIAI · YOUR 7-DAY PLAN", MARGIN, y);
    y += 6;

    setColor(ACCENT);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text(`DAY ${dayData.day}`, MARGIN, y);

    setColor(TEXT);
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text(DAY_NAMES[di] ?? `Day ${dayData.day}`, MARGIN + 22, y);
    y += 6;
    line(y);
    y += 6;

    // Daily totals strip
    const dTotals = dayData.meals.reduce(
      (a, m) => ({ kcal: a.kcal+m.kcal, protein: a.protein+m.protein, carbs: a.carbs+m.carbs, fat: a.fat+m.fat }),
      { kcal:0, protein:0, carbs:0, fat:0 }
    );
    rect(MARGIN, y, COL, 14, CARD);
    const dStats = [`${dTotals.kcal} kcal`, `${dTotals.protein}g protein`, `${dTotals.carbs}g carbs`, `${dTotals.fat}g fat`];
    dStats.forEach((s, i) => {
      setColor(i === 0 ? ACCENT : MUTED);
      doc.setFontSize(9);
      doc.setFont("helvetica", i === 0 ? "bold" : "normal");
      doc.text(s, MARGIN + 5 + i * (COL / 4), y + 9);
    });
    y += 20;

    // Meals
    dayData.meals.forEach((meal) => {
      if (y > 250) { doc.addPage(); rect(0,0,W,297,BG); y = 16; }

      // Meal name + time
      setColor(TEXT);
      doc.setFontSize(13);
      doc.setFont("helvetica", "bold");
      doc.text(meal.name, MARGIN, y);

      setColor(MUTED);
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.text(meal.time, MARGIN + doc.getTextWidth(meal.name) + 4, y);

      // Macros right-aligned
      setColor(ACCENT);
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.text(`${meal.kcal} kcal`, W - MARGIN, y, { align: "right" });

      setColor(MUTED);
      doc.setFontSize(7.5);
      doc.setFont("helvetica", "normal");
      const macroLine = `${meal.protein}g protein  ${meal.carbs}g carbs  ${meal.fat}g fat`;
      doc.text(macroLine, W - MARGIN, y + 5, { align: "right" });

      y += 10;

      // Items
      meal.items.forEach((item) => {
        if (y > 272) { doc.addPage(); rect(0,0,W,297,BG); y = 16; }
        setColor(MUTED);
        doc.setFontSize(7);
        doc.text("—", MARGIN + 2, y);
        setColor(TEXT);
        doc.setFontSize(8.5);
        const wrapped = doc.splitTextToSize(item, COL - 20);
        doc.text(wrapped, MARGIN + 7, y);
        y += wrapped.length * 5;
      });

      y += 4;
      line(y);
      y += 7;
    });

    // Nutritionist note
    if (dayData.notes) {
      if (y > 240) { doc.addPage(); rect(0,0,W,297,BG); y = 16; }
      rect(MARGIN, y, 2, 18, ACCENT);
      setColor(MUTED);
      doc.setFontSize(7);
      doc.setFont("helvetica", "bold");
      doc.text("NUTRITIONIST NOTE", MARGIN + 6, y + 5);
      setColor(TEXT);
      doc.setFontSize(8.5);
      doc.setFont("helvetica", "italic");
      const noteLines = doc.splitTextToSize(dayData.notes, COL - 12);
      doc.text(noteLines, MARGIN + 6, y + 11);
    }

    // Page footer
    setColor(MUTED);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.text(`NutriAI · ${userName} · Page ${di + 2}`, W - MARGIN, 290, { align: "right" });
  });

  const dateStr = new Date().toISOString().slice(0, 10);
  doc.save(`NutriAI-Plan-${dateStr}.pdf`);
}
